version: '2'
services:
  redis:
    image: redis:3.0.7-alpine
    container_name: registry-redis
    restart: always
    network_mode: host
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://log:514"
        tag: "registry-redis"