---
- hosts: appcenter
  remote_user: root
  no_log: True
  gather_facts: no
  vars:
    harborVersion: v1.7.0

  tasks:
    - name: Copy confd toml files
      copy:
        src: files/etc/confd/conf.d/make.sh.toml
        dest: /etc/confd/conf.d/make.sh.toml

    - name: Compile tmpl files
      raw: |
        srcDir=files/etc/confd
        destDir=files/tmp/confd
        rm -rf $destDir
        mkdir -p $destDir/{conf.d,templates}
        tmplFile=$destDir/templates/make.sh.tmpl
        echo "#!/usr/bin/env bash" >> $tmplFile
        echo "set -e" >> $tmplFile
        echo '{{ '{{' }} $nodeRole := index (split (getv "/host/role") "_node") 0 }}' >> $tmplFile
        for tmpl in $(ls $srcDir/templates/*); do
          echo "######## templates from `basename $tmpl`" >> $tmplFile
          cat $tmpl >> $tmplFile
        done
      delegate_to: localhost

    - name: Copy confd tmpl files
      copy:
        src: files/tmp/confd/templates/make.sh.tmpl
        dest: /etc/confd/templates/make.sh.tmpl

    - name: Copy Docker registry mirror configuration file to speed up image pulling
      copy:
        src: files/etc/docker/
        dest: /etc/docker/
        directory_mode: yes

    - name: Copy Binaries
      copy:
        src: files/opt/
        dest: /opt/
        directory_mode: yes

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

    - name: Install Tools
      apt:
        update_cache: yes
        name: ['nfs-common', 'docker-ce']
        state: present

    # - name: Restart Docker Daemon to respect registry mirror configuration
    #   service:
    #     name: docker
    #     state: restarted

    - name: Pull Docker Images
      command: docker pull {{ item }}
      # retries: 3
      # delay: 3
      with_items:
        - "vmware/harbor-db-migrator:1.3"
        - "goharbor/harbor-migrator:v1.6.0"
        - "goharbor/harbor-migrator:{{ harborVersion }}"
        - "goharbor/redis-photon:{{ harborVersion }}"
        - "goharbor/harbor-registryctl:{{ harborVersion }}"
        - "goharbor/registry-photon:v2.6.2-{{ harborVersion }}"
        - "goharbor/nginx-photon:{{ harborVersion }}"
        - "goharbor/harbor-log:{{ harborVersion }}"
        - "goharbor/harbor-jobservice:{{ harborVersion }}"
        - "goharbor/harbor-core:{{ harborVersion }}"
        - "goharbor/harbor-portal:{{ harborVersion }}"
        - "goharbor/harbor-adminserver:{{ harborVersion }}"
        - "goharbor/harbor-db:{{ harborVersion }}"
        - "erichough/nfs-server:1.2.0"

    - name: Download reusable Docker Compose binaries locally
      get_url:
        url: https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64
        dest: files/tmp/docker-compose
      delegate_to: localhost

    - name: Copy Binaries
      copy:
        src: files/tmp/docker-compose
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Prepare directories for Harbor
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /data
        - /opt/app/conf/adminserver
        - /opt/app/conf/db

    - name: Protect binaries and configurations
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rx,o=
        owner: 0
        group: 10000
        recurse: yes
      with_items:
        - /etc/confd
        - /opt

    - name: Clean up
      raw: |
        chown 0.999 /opt/app/conf/redis/redis.conf
        >/var/log/syslog
        >~/.bash_history && history -c
