---
- name: tasks
  hosts: all
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ name }}"
    loop:
    - disable-apt-jobs-1.0.0
    - disable-motd-1.0.0
    - app-agent-1.0.1
    - appctl-1.0.5
    - arping-1.0.0
    - caddy-1.0.6
    - jq-1.0.3
    - harbor
    loop_control:
      loop_var: name
